### ISSUE TITLE
I cannot install the dependency

### ISSUE THREAD

**Issue by angolini** [molejar/pyIMX#1]
I run the dependency installation command but I face a dependency error.

```
:~/pyIMX$ pip3 install -U --process-dependency-links -e .
Obtaining file:///home/daiane/pyIMX
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "./src/imx/sd/usbif.py", line 174, in <module>
        import usb.core
    ImportError: No module named 'usb'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/daiane/pyIMX/setup.py", line 22, in <module>
        import imx
      File "./src/imx/__init__.py", line 20, in <module>
        from .sd import SerialDownloader, \
      File "./src/imx/sd/__init__.py", line 16, in <module>
        from .serdown import SerialDownloader, \
      File "./src/imx/sd/serdown.py", line 20, in <module>
        from .usbif import USBIF
      File "./src/imx/sd/usbif.py", line 177, in <module>
        raise Exception("PyUSB is required on a Linux Machine")
    Exception: PyUSB is required on a Linux Machine
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/daiane/pyIMX
```/


Can you, please, help?

**Comment by molejar** [comment]
You need install all required modules manualy, because your version of pip
has blocked the instalation of dependencies automaticly (secure settings).
The name of modules you find in setup.py. Only run pip install pyusb click
...

Dne 20. 10. 2017 18:28 napsal uživatel "Daiane Angolini" <
notifications@github.com>:

**Comment by angolini** [comment]
Thanks I'm going to try.

Is there something you could add to the README to try to avoid this king of mistake?

**Comment by molejar** [comment]
Fixed, please try it
